version: "3.8"

services:
  webserver:
    build: ./nginx
    container_name: test-webserver
    ports:
      - 80:80
    volumes:
      - ./www/html/:/var/www/html/
# ############
  app:
    image: php:8.0-fpm
    container_name: test-app
    volumes:
      - ./www/html/:/var/www/html/