version: "3.8"

services:
  webserver:
    build: ./nginx
    container_name: test-webserver
    ports:
      - 80:80
    volumes:
      - ./www/html/:/var/www/html/
    networks:
      - test
##############
  app:
    build: ./php/
    container_name: test-app
    volumes:
      - ./www/html/:/var/www/html/
    networks:
      - test
##############
  db:
    image: mysql:5.7
    container_name: test-db
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - 'test-mysql:/var/lib/mysql'
    environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_DATABASE: mydb
       MYSQL_USER: myuser
       MYSQL_PASSWORD: password
    networks:
      - test

networks:
  test:
    name: test-network

volumes:
  test-mysql: